export const uzbekistanLocations = {
  "Toshkent shahri": [
    "Bektemir tumani",
    "Chilonzor tumani",
    "Mirobod tumani",
    "Mirzo Ulug‘bek tumani",
    "Olmazor tumani",
    "Sergeli tumani",
    "Shayxontohur tumani",
    "Uchtepa tumani",
    "Yakkasaroy tumani",
    "Yashnobod tumani",
    "Yunusobod tumani",
    "Yangihayot tumani",
  ],
  "Toshkent viloyati": [
    "Angren",
    "Bekobod",
    "Chirchiq",
    "Nurafshon",
    "Olmaliq",
    "Ohangaron",
    "Parkent",
    "Qibray",
    "Yangiyo‘l",
    "Zangiota",
  ],
  "Andijon viloyati": [
    "Andijon",
    "Asaka",
    "Baliqchi",
    "Bo‘ston",
    "Marhamat",
    "Shahrixon",
    "Xonobod",
  ],
  "Buxoro viloyati": [
    "Buxoro",
    "G‘ijduvon",
    "Kogon",
    "Qorako‘l",
    "Romitan",
    "Vobkent",
  ],
  "Farg‘ona viloyati": [
    "Farg‘ona",
    "Marg‘ilon",
    "Oltiariq",
    "Qo‘qon",
    "Quva",
    "Quvasoy",
    "Rishton",
  ],
  "Jizzax viloyati": [
    "Arnasoy",
    "Baxmal",
    "Do‘stlik",
    "G‘allaorol",
    "Jizzax",
    "Zomin",
  ],
  "Namangan viloyati": [
    "Chortoq",
    "Chust",
    "Kosonsoy",
    "Namangan",
    "Pop",
    "To‘raqo‘rg‘on",
    "Uchqo‘rg‘on",
  ],
  "Navoiy viloyati": [
    "Karmana",
    "Konimex",
    "Navoiy",
    "Nurota",
    "Qiziltepa",
    "Zarafshon",
  ],
  "Qashqadaryo viloyati": [
    "Chiroqchi",
    "G‘uzor",
    "Kitob",
    "Koson",
    "Qarshi",
    "Shahrisabz",
  ],
  "Qoraqalpog‘iston Respublikasi": [
    "Beruniy",
    "Chimboy",
    "Mo‘ynoq",
    "Nukus",
    "Qo‘ng‘irot",
    "To‘rtko‘l",
    "Xo‘jayli",
  ],
  "Samarqand viloyati": [
    "Bulung‘ur",
    "Ishtixon",
    "Jomboy",
    "Kattaqo‘rg‘on",
    "Narpay",
    "Samarqand",
    "Urgut",
  ],
  "Sirdaryo viloyati": [
    "Boyovut",
    "Guliston",
    "Sardoba",
    "Shirin",
    "Sirdaryo",
    "Yangiyer",
  ],
  "Surxondaryo viloyati": [
    "Boysun",
    "Denov",
    "Jarqo‘rg‘on",
    "Sherobod",
    "Termiz",
    "Uzun",
  ],
  "Xorazm viloyati": [
    "Bog‘ot",
    "Gurlan",
    "Hazorasp",
    "Shovot",
    "Urganch",
    "Xiva",
  ],
} as const;

export type UzbekistanRegion = keyof typeof uzbekistanLocations;

export const uzbekistanRegions = Object.keys(
  uzbekistanLocations,
) as UzbekistanRegion[];
